"""Creating and maintaining affiliates.

Nothing here decides what anyone is owed - that is Phase 4. This is the
registry: who exists, what kind of account they are, and where they are in
their life with the business.
"""

import re
import secrets

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.core.businesstime import business_month, utcnow
from app.core.periods import PLATFORM_START_MONTH
from app.core.passwords import hash_password
from app.models.affiliates import (
    VALID_KINDS,
    VALID_STATUSES,
    AccountKind,
    AffiliateProfile,
    AffiliateStatus,
)
from app.models.codes import DiscountCodePeriod
from app.models.compensation import CompensationPeriod
from app.models.identity import UserAccount
from app.services.audit import record_audit
from app.services.codes import close_codes_for, verified_codes_for


def create_affiliate(
    db: Session,
    *,
    user_account_id: int,
    name: str,
    phone: str | None = None,
    account_kind: str = AccountKind.MODEL,
    actor_id: int | None = None,
    actor_email: str | None = None,
) -> AffiliateProfile:
    """Register an affiliate against an existing account.

    Created ``pending``: applied, not yet approved. Approval is a deliberate
    later act, after the discount code has been verified against Shopify
    (§10.4) and compensation terms are set.
    """
    if account_kind not in VALID_KINDS:
        raise ValueError(f"Unknown account kind: {account_kind!r}")

    affiliate = AffiliateProfile(
        user_account_id=user_account_id,
        name=str(name or "").strip(),
        phone=(str(phone).strip() or None) if phone else None,
        account_kind=account_kind,
        status=AffiliateStatus.PENDING,
    )
    db.add(affiliate)
    db.flush()

    record_audit(
        db,
        action="affiliate.created",
        subject=f"affiliate:{affiliate.id}",
        actor_id=actor_id,
        actor_email=actor_email,
        after={"name": affiliate.name, "account_kind": account_kind},
    )
    return affiliate


def _house_account_email(name: str) -> str:
    """A synthetic address, obviously not a person's, for a house account's
    `user_account` row. Not shown anywhere - it exists to satisfy a `NOT NULL`
    foreign key, never to be typed by anyone.
    """
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-") or "code"
    return f"house.{slug}@hba-platform.internal"


def create_house_account(
    db: Session,
    *,
    name: str,
    actor_id: int | None = None,
    actor_email: str | None = None,
) -> AffiliateProfile:
    """A discount code that is HBA's own, not a person's - HBA10 and anything
    like it.

    Every affiliate hangs off a `user_account`, and that column is deliberately
    not nullable (ADR 0006): identity lives in one place, not in a
    special-cased second shape for the one row that is not a person. So a
    house account gets a real `user_account` too - one that can never be
    signed into.

    `status="suspended"` is the same state a real person's account is put
    into to lock them out after the fact; here it starts there and never
    leaves. The password is generated by `secrets`, hashed, and told to
    nobody - not logged, not returned, not knowable even by whoever is
    reading this - so a locked status is not the only thing standing between
    this account and a session.

    Returns the affiliate `pending`, exactly like `create_affiliate` does.
    Registering and verifying its code, and approving it once verified, are
    separate acts the caller performs next - this only brings the account
    into existence.
    """
    account = UserAccount(
        email=_house_account_email(name),
        password_hash=hash_password(secrets.token_urlsafe(48)),
        status="suspended",
        display_name=name,
    )
    db.add(account)
    db.flush()

    return create_affiliate(
        db,
        user_account_id=account.id,
        name=name,
        account_kind=AccountKind.HOUSE,
        actor_id=actor_id,
        actor_email=actor_email,
    )


def set_status(
    db: Session,
    affiliate: AffiliateProfile,
    status: str,
    *,
    actor_id: int | None = None,
    actor_email: str | None = None,
    reason: str | None = None,
) -> None:
    """Move an affiliate to a new status, recording what it changed from.

    "Who deactivated Nour, and when" is a question that gets asked, and the new
    value alone does not answer it.

    Setting the status it already has records nothing. An audit trail full of
    non-events is one nobody reads.
    """
    if status not in VALID_STATUSES:
        raise ValueError(f"Unknown affiliate status: {status!r}")

    previous = affiliate.status
    if previous == status:
        return

    if status == AffiliateStatus.ACTIVE and not verified_codes_for(db, affiliate):
        # Spec 10.4: Shopify code verification is a *required gate* before
        # approval, and this is the gate.
        #
        # Approving a mistyped code is the failure it exists to catch. Nothing
        # errors: the code simply matches no order, the model earns nothing,
        # and the first anyone notices is when they ask why their dashboard is
        # empty - by which point months of their sales have gone to nobody.
        #
        # Enforced here rather than in the API so it holds for every caller,
        # the same reasoning as closing code ownership on archive.
        raise ValueError(
            "This affiliate has no code confirmed to exist in Shopify. Verify "
            "the code first - an unverified code that turns out to be mistyped "
            "attributes nothing, silently."
        )

    affiliate.status = status

    # Section 16, and the email the whole go-live depends on arriving. Only on
    # the transition into `active` from a pending application - reactivating a
    # paused model is not the same event and they have already been welcomed.
    if status == AffiliateStatus.ACTIVE and previous == AffiliateStatus.PENDING:
        from app.services.notifications import application_approved

        application_approved(db, affiliate)

    record_audit(
        db,
        action="affiliate.status_changed",
        subject=f"affiliate:{affiliate.id}",
        actor_id=actor_id,
        actor_email=actor_email,
        before={"status": previous},
        after={"status": status},
        reason=reason,
    )


def archive_affiliate(
    db: Session,
    affiliate: AffiliateProfile,
    *,
    actor_id: int | None = None,
    actor_email: str | None = None,
    reason: str | None = None,
) -> None:
    """Retire an affiliate without removing them.

    Nothing is deleted: an archived affiliate's past payroll still has to
    resolve, and so does every payment already made to them.

    The timestamp is set once. When somebody left is a fact, not a function of
    who pressed the button last.

    **Also closes any code they still hold**, from this month forward. Archiving
    says "from now on, not theirs"; it must never say "was never theirs" -
    close_codes_for only touches open-ended periods and only from the current
    month on, so nothing already approved and paid is rewritten. Without this,
    an archived affiliate would keep silently owning their code, and an order
    placed after they left would still attribute to them.
    """
    now = utcnow()
    if affiliate.archived_at is None:
        affiliate.archived_at = now

    close_codes_for(
        db,
        affiliate,
        business_month(now),
        actor_id=actor_id,
        actor_email=actor_email,
    )

    set_status(
        db,
        affiliate,
        AffiliateStatus.ARCHIVED,
        actor_id=actor_id,
        actor_email=actor_email,
        reason=reason,
    )


def update_details(
    db: Session,
    affiliate: AffiliateProfile,
    *,
    name: str | None = None,
    phone: str | None = None,
    email: str | None = None,
    actor_id: int | None = None,
    actor_email: str | None = None,
) -> None:
    """Correct what a model submitted about themselves.

    They fill their own details in, and people mistype their own phone numbers.
    Without this the only fix would be deleting the account and starting over.

    **Email is their login**, so changing it is a real change and not a contact
    edit - the account they sign in with moves. It is recorded like any other,
    with what it changed from, because "why can they not sign in any more" is a
    question that gets asked.

    Only supplied fields change. Passing nothing is not an error, and records
    nothing.
    """
    before: dict = {}
    after: dict = {}

    if name is not None and (cleaned := name.strip()) and cleaned != affiliate.name:
        before["name"], after["name"] = affiliate.name, cleaned
        affiliate.name = cleaned

    if phone is not None:
        cleaned_phone = phone.strip() or None
        if cleaned_phone != affiliate.phone:
            before["phone"], after["phone"] = affiliate.phone, cleaned_phone
            affiliate.phone = cleaned_phone

    if email is not None and (cleaned_email := email.strip().lower()):
        account = affiliate.account
        if cleaned_email != account.email:
            before["email"], after["email"] = account.email, cleaned_email
            account.email = cleaned_email

    if not after:
        return

    record_audit(
        db,
        action="affiliate.details_updated",
        subject=f"affiliate:{affiliate.id}",
        actor_id=actor_id,
        actor_email=actor_email,
        before=before,
        after=after,
    )


def set_collaboration_start(
    db: Session,
    affiliate: AffiliateProfile,
    month: str | None,
    *,
    actor_id: int | None = None,
    actor_email: str | None = None,
) -> None:
    """Record the month she actually started with HBA.

    **Nothing derives this and nothing ever will**, which is the reason the
    column exists. Rule H01: a code's first order, the invitation and the
    platform signup are three different dates, none of them this one, and they
    agree often enough that using one as a proxy fails quietly rather than
    loudly. So it is entered, by somebody who knows, per model.

    Refuses a month before the platform's data horizon. Not because a model
    cannot have started earlier — many did — but because there are no orders
    before `PLATFORM_START_MONTH` for the platform to show her, so a start of
    `2025-04` would open eleven months that are empty for a reason nothing on
    the screen could explain. Her real earlier history was settled outside and
    stays there (H03).

    Refuses a month in the future for the same class of reason: it would offer
    her a month that has not happened.

    `None` clears it, and clearing is a real answer — it puts her back on the
    derivation until somebody knows better. Recorded either way, because "who
    said she started in March" is a question that decides which months she can
    open.
    """
    # Imported here rather than at the top: `payroll` pulls in the commission
    # engine, and this module is imported by half of it. The codebase already
    # does this where the same knot appears - see `carried_forward`.
    from app.services.payroll import working_month

    cleaned = (month or "").strip() or None

    if cleaned is not None:
        if not re.fullmatch(r"[0-9]{4}-(0[1-9]|1[0-2])", cleaned):
            raise ValueError("A start month looks like 2026-03")
        if cleaned < PLATFORM_START_MONTH:
            raise ValueError(
                f"The platform holds no orders before {PLATFORM_START_MONTH}, "
                "so a start before then would open months it cannot explain. "
                "Months settled before the platform are handled separately."
            )
        if cleaned > working_month():
            raise ValueError("A start month cannot be in the future")

    if cleaned == affiliate.collaboration_start_month:
        return

    before = {"collaboration_start_month": affiliate.collaboration_start_month}
    affiliate.collaboration_start_month = cleaned

    record_audit(
        db,
        action="affiliate.collaboration_start_set",
        subject=f"affiliate:{affiliate.id}",
        actor_id=actor_id,
        actor_email=actor_email,
        before=before,
        after={"collaboration_start_month": cleaned},
    )


def update_measurements(
    db: Session,
    affiliate: AffiliateProfile,
    *,
    height_cm: int | None = None,
    weight_kg: int | None = None,
    actor_id: int | None = None,
    actor_email: str | None = None,
) -> None:
    """Her own measurements, written by her.

    **Rule A05: a model edits these and staff read them.** There is no admin
    path into this function, and that is the enforcement — a permission check
    here would still be a function an admin route could call, and the point is
    that no such route exists. Staff see the values on her profile and have
    nowhere to type into.

    Both are optional at every point in her life with the business. Missing is
    a normal state and never blocks anything (A05), so `None` for a field means
    *leave it alone* and an explicitly cleared value is written as `None`
    rather than as a zero — a zero would be a measurement.

    Bounds are checked here as well as in the database, so the message a person
    reads says what a height is rather than naming a constraint.
    """
    before: dict = {}
    after: dict = {}

    def _clean(value, label: str, low: int, high: int):
        if value is None:
            return None
        if isinstance(value, str) and not value.strip():
            return None
        try:
            number = int(value)
        except (TypeError, ValueError):
            raise ValueError(f"{label} should be a number") from None
        if not low <= number <= high:
            raise ValueError(f"{label} should be between {low} and {high}")
        return number

    if height_cm is not None:
        cleaned = _clean(height_cm, "A height in centimetres", 100, 250)
        if cleaned != affiliate.height_cm:
            before["height_cm"], after["height_cm"] = affiliate.height_cm, cleaned
            affiliate.height_cm = cleaned

    if weight_kg is not None:
        cleaned = _clean(weight_kg, "A weight in kilograms", 30, 250)
        if cleaned != affiliate.weight_kg:
            before["weight_kg"], after["weight_kg"] = affiliate.weight_kg, cleaned
            affiliate.weight_kg = cleaned

    if not after:
        return

    # Recorded without the values. They are hers, the audit trail is read by
    # staff who may not change them, and "she updated her measurements" is the
    # whole of what an audit needs to know.
    record_audit(
        db,
        action="affiliate.measurements_updated",
        subject=f"affiliate:{affiliate.id}",
        actor_id=actor_id,
        actor_email=actor_email,
        before={key: before[key] is not None for key in before},
        after={key: after[key] is not None for key in after},
    )


def get_affiliate(db: Session, affiliate_id: int) -> AffiliateProfile | None:
    """One affiliate, archived or not. History has to stay reachable."""
    return db.get(AffiliateProfile, affiliate_id)


def list_affiliates(
    db: Session, *, include_archived: bool = False
) -> list[AffiliateProfile]:
    """Every affiliate, by name.

    Archived ones are excluded by default: the common question is "who is on
    the programme", not "who ever was".
    """
    query = select(AffiliateProfile).order_by(AffiliateProfile.name)
    if not include_archived:
        query = query.where(AffiliateProfile.status != AffiliateStatus.ARCHIVED)
    return list(db.scalars(query))


def _covers(month: str, start_month, end_month):
    """Rows whose effective period contains `month`.

    An open-ended period - `end_month` null - runs until something closes it,
    so it covers every month from its start onwards.
    """
    return (start_month <= month) & (
        (end_month.is_(None)) | (end_month >= month)
    )


def readiness(db: Session, month: str) -> dict[int, dict[str, bool]]:
    """Per affiliate, whether the two things they need in order to earn exist.

    A model earns nothing without **a code Shopify has confirmed** and **terms
    saying what they are paid**. Either one missing is silent: orders arrive,
    attribution finds no owner or the calculator finds no rate, and the first
    anybody hears of it is the model asking why their dashboard is empty. The
    list screen exists to catch that before they have to ask.

    Two set-based queries rather than two per affiliate. Twenty models would
    otherwise be forty round trips for something the database answers in two -
    and the cost of getting this wrong grows exactly as the programme grows.
    """
    with_code = set(
        db.scalars(
            select(DiscountCodePeriod.affiliate_id)
            .where(DiscountCodePeriod.shopify_verified_at.is_not(None))
            .where(
                _covers(
                    month,
                    DiscountCodePeriod.start_month,
                    DiscountCodePeriod.end_month,
                )
            )
        )
    )
    with_terms = set(
        db.scalars(
            select(CompensationPeriod.affiliate_id).where(
                _covers(
                    month,
                    CompensationPeriod.start_month,
                    CompensationPeriod.end_month,
                )
            )
        )
    )

    return {
        affiliate_id: {
            "has_verified_code": affiliate_id in with_code,
            "has_terms": affiliate_id in with_terms,
        }
        for affiliate_id in db.scalars(select(AffiliateProfile.id))
    }

