import { Link } from "react-router-dom";

import { formatMonth, shortMonth } from "../lib/money";
import "./SalesByMonth.css";

export type YearMonth = {
  month: string;
  sales_piastres: number;
  /** Already formatted by the server. Nothing here divides by a hundred. */
  sales: string;
};

/**
 * *Sales generated, EGP per month* — the last block on the approved Home.
 *
 * ## Why it exists at all
 *
 * It was left out, and the comment left in its place said *nothing here is a
 * chart; twenty rows is not a dataset*. That is a fair rule about a **table**
 * of twenty models and it is not what this draws: eleven months of one figure
 * is a shape, and a shape is the one thing a column of numbers cannot show —
 * that March was half of February, that the year is climbing, that a month
 * nobody noticed was empty. The approved design draws it, and the reason it
 * draws it is that the owner asked *how are we doing*, which is not a
 * question about this month.
 *
 * ## Nothing here computes money
 *
 * The bar heights are a ratio of two figures the server sent, which is
 * geometry. Every number a reader can actually see — each bar's title, the
 * top of the axis — is the server's own formatted string, reprinted. The axis
 * middle is deliberately unlabelled rather than half of something: half of a
 * month's sales is a figure nobody sent, and inventing one here would be the
 * second implementation this codebase refuses.
 */
export function SalesByMonth({
  year,
  month,
  onPick,
}: {
  year: YearMonth[];
  month: string;
  onPick?: (month: string) => void;
}) {
  if (year.length === 0) return null;

  const top = year.reduce(
    (highest, row) => Math.max(highest, row.sales_piastres),
    0,
  );
  const peak = year.find((row) => row.sales_piastres === top);

  /* The export's own frame: 580 wide, 130 of plot, and the month names on the
     baseline under it. */
  const WIDTH = 580;
  const PLOT = 130;
  const slot = WIDTH / year.length;
  const bar = Math.min(slot * 0.62, 46);

  return (
    <section className="sales-year" aria-label="Sales generated by month">
      <div className="sales-year__head">
        <h2 className="sales-year__title">Sales generated, EGP per month</h2>
        <span className="sales-year__range">
          {formatMonth(year[0].month)} – {formatMonth(year[year.length - 1].month)}
        </span>
      </div>

      {/*
       * The axis labels sit **inside** the plot rather than in a gutter to
       * its left. The export can put them outside because its sample figures
       * are three characters wide; ours are the server's full `EGP 63,235.70`,
       * which at this scale is wider than the whole gutter and spilled off
       * the card's left edge. Inside, anchored to the start, it fits at any
       * length and still reads as the top of the scale.
       */}
      <svg className="sales-year__chart" viewBox="0 -14 580 168" role="img"
        aria-label={`Sales generated each month, highest ${peak?.sales ?? "0"}`}>
        {[0, PLOT / 2, PLOT].map((y) => (
          <line key={y} x1="0" x2={WIDTH} y1={y} y2={y}
            stroke="var(--rule-strong)" strokeWidth="1" />
        ))}
        <text x="0" y="-4" textAnchor="start" fontSize="10" fill="var(--faint)">
          {peak?.sales ?? ""}
        </text>
        <text x="0" y={PLOT + 11} textAnchor="start" fontSize="10" fill="var(--faint)">
          0
        </text>

        {year.map((row, index) => {
          const height = top === 0 ? 0 : (row.sales_piastres / top) * PLOT;
          const x = index * slot + (slot - bar) / 2;
          const chosen = row.month === month;
          return (
            <rect key={row.month} x={x} y={PLOT - height} width={bar}
              height={Math.max(height, 1)} rx="3"
              className={chosen ? "sales-year__bar sales-year__bar--on" : "sales-year__bar"}
              onClick={onPick ? () => onPick(row.month) : undefined}>
              <title>{`${formatMonth(row.month)} · ${row.sales}`}</title>
            </rect>
          );
        })}

        {year.map((row, index) => (
          <text key={row.month} x={index * slot + slot / 2} y="150"
            textAnchor="middle" fontSize="10"
            fill={row.month === month ? "var(--ink)" : "var(--faint)"}>
            {shortMonth(row.month)}
          </text>
        ))}
      </svg>

      {/* A bar is a link for anybody not using a mouse: the export makes each
       *  one switch the month, and a `<rect>` with an `onClick` is reachable
       *  by nothing else. */}
      <ul className="sales-year__months">
        {year.map((row) => (
          <li key={row.month}>
            <Link to={`/?month=${row.month}`}>
              {formatMonth(row.month)} · {row.sales}
            </Link>
          </li>
        ))}
      </ul>
    </section>
  );
}
