import { Link } from "react-router-dom";

import { formatMonth, shortMonth } from "../lib/money";
import { axisLabels } from "./PortalYearChart";
import "./SalesByMonth.css";

export type YearMonth = {
  month: string;
  sales_piastres: number;
  /** Already formatted by the server. Nothing here divides by a hundred. */
  sales: string;
};

/**
 * *Sales generated, EGP per month* — the last block on the approved Home.
 *
 * ## Why it exists at all
 *
 * It was left out, and the comment left in its place said *nothing here is a
 * chart; twenty rows is not a dataset*. That is a fair rule about a **table**
 * of twenty models and it is not what this draws: eleven months of one figure
 * is a shape, and a shape is the one thing a column of numbers cannot show —
 * that March was half of February, that the year is climbing, that a month
 * nobody noticed was empty. The approved design draws it, and the reason it
 * draws it is that the owner asked *how are we doing*, which is not a
 * question about this month.
 *
 * ## Nothing here computes money
 *
 * The bar heights are a ratio of two figures the server sent, which is
 * geometry. Each bar's title is the server's own formatted string. The three
 * rules are labelled as the portal's are (the owner's *readable axes from
 * real figures*, 24 September): the scale's own points, in whole pounds or
 * *K* - a place on a ruler, never a figure somebody is owed.
 */
export function SalesByMonth({
  year,
  month,
  onPick,
}: {
  year: YearMonth[];
  month: string;
  onPick?: (month: string) => void;
}) {
  if (year.length === 0) return null;

  const top = year.reduce(
    (highest, row) => Math.max(highest, row.sales_piastres),
    0,
  );
  const peak = year.find((row) => row.sales_piastres === top);

  /* The export's own frame (Admin lines 237-250, `chartGrid`/`chartBars`):
     580 wide with a 30px gutter to its left for the rule labels, rules at
     18, 68 and 118, bars 56% of their slot from 22% in, at least 2 high, and
     the month names on 140. */
  const WIDTH = 580;
  const BASE = 118;
  const PLOT = 100;
  const step = WIDTH / year.length;
  const labels = axisLabels(top, "sales");

  return (
    <section className="sales-year" aria-label="Sales generated by month">
      <div className="sales-year__head">
        <h2 className="sales-year__title">Sales generated, EGP per month</h2>
        <span className="sales-year__range">
          {/* The export's *January – November 2026*: one year said once. */}
          {year[0].month.slice(0, 4) === year[year.length - 1].month.slice(0, 4)
            ? `${formatMonth(year[0].month).split(" ")[0]} – ${formatMonth(year[year.length - 1].month)}`
            : `${formatMonth(year[0].month)} – ${formatMonth(year[year.length - 1].month)}`}
        </span>
      </div>

      {/* The rule labels sit **outside** the plot, in the export's gutter:
       *  compact labels (*85K*) fit there, where the full *EGP 63,235.70*
       *  did not and had been moved inside. */}
      <svg className="sales-year__chart" viewBox="-30 0 620 150" role="img"
        aria-label={`Sales generated each month, highest ${peak?.sales ?? "0"}`}>
        {[0, 0.5, 1].map((f, index) => (
          <g key={f}>
            <line x1="0" x2={WIDTH} y1={BASE - PLOT * f} y2={BASE - PLOT * f}
              stroke="var(--rule-strong)" strokeWidth="1" />
            <text x="-8" y={BASE - PLOT * f + 3.5} textAnchor="end" fontSize="10" fill="var(--faint)">
              {labels[index]}
            </text>
          </g>
        ))}

        {year.map((row, index) => {
          const height = Math.max(top === 0 ? 0 : (PLOT * row.sales_piastres) / top, 2);
          const chosen = row.month === month;
          return (
            <rect key={row.month} x={step * index + step * 0.22} y={BASE - height}
              width={step * 0.56} height={height} rx="3"
              className={chosen ? "sales-year__bar sales-year__bar--on" : "sales-year__bar"}
              onClick={onPick ? () => onPick(row.month) : undefined}>
              <title>{`${formatMonth(row.month)} · ${row.sales}`}</title>
            </rect>
          );
        })}

        {year.map((row, index) => (
          <text key={row.month} x={step * index + step * 0.5} y="140"
            textAnchor="middle" fontSize="10"
            fill={row.month === month ? "var(--accent)" : "var(--faint)"}>
            {shortMonth(row.month)}
          </text>
        ))}
      </svg>

      {/* A bar is a link for anybody not using a mouse: the export makes each
       *  one switch the month, and a `<rect>` with an `onClick` is reachable
       *  by nothing else. */}
      <ul className="sales-year__months">
        {year.map((row) => (
          <li key={row.month}>
            <Link to={`/?month=${row.month}`}>
              {formatMonth(row.month)} · {row.sales}
            </Link>
          </li>
        ))}
      </ul>
    </section>
  );
}
