import pytest
from sqlalchemy import text

from app.db import engine


def test_database_is_reachable():
    with engine.connect() as connection:
        assert connection.execute(text("SELECT 1")).scalar() == 1


def test_alembic_version_table_exists_after_upgrade():
    with engine.connect() as connection:
        result = connection.execute(
            text(
                "SELECT COUNT(*) FROM information_schema.tables "
                "WHERE table_name = 'alembic_version'"
            )
        ).scalar()
    assert result == 1, "run: alembic upgrade head"


def test_no_schema_drift_between_the_models_and_the_migrations(db):
    """The models and the migrated schema must describe the same database.

    Caught a real one: `effective_range` is created by a migration and was not
    declared on the model, so Alembic saw a column the models did not have.
    The next --autogenerate would have written a migration DROPPING it - and
    the exclusion constraint that stops two affiliates owning one code goes
    with the column.

    Nothing would have failed. The constraint would simply have stopped
    existing, and the next overlapping registration would have been accepted.
    """
    from alembic import command
    from alembic.config import Config
    from alembic.util.exc import AutogenerateDiffsDetected

    try:
        command.check(Config("alembic.ini"))
    except AutogenerateDiffsDetected as drift:
        raise AssertionError(
            f"The models and the migrations disagree: {drift}\n"
            "Either add the missing migration, or declare the column on the "
            "model - but do not let --autogenerate decide, because its answer "
            "to an undeclared column is to drop it."
        ) from drift


def test_emptying_the_database_leaves_the_guards_on():
    """The fast reset disables user triggers for one transaction so TRUNCATE
    can pass the append-only guards. If that setting leaked - a session-level
    SET riding along on a pooled connection - the guards would be off for
    whatever ran next, and a later test would pass for the wrong reason.

    So: empty the database, then prove an audit event still cannot be edited.
    """
    from sqlalchemy import text as sql_text

    from app.db import engine
    from tests.conftest import empty_the_database

    empty_the_database()

    with engine.begin() as connection:
        connection.execute(
            sql_text("INSERT INTO audit_event (action, subject) VALUES ('t', 's')")
        )

    with pytest.raises(Exception):
        with engine.begin() as connection:
            connection.execute(sql_text("UPDATE audit_event SET action = 'x'"))

    empty_the_database()


def test_emptying_the_database_keeps_the_schema_migrated():
    """`alembic_version` is excluded on purpose. Emptying it would make the
    schema look unmigrated and send the next run through every migration again
    - which is the cost this whole change exists to remove.
    """
    from sqlalchemy import text as sql_text

    from app.db import engine
    from tests.conftest import empty_the_database

    empty_the_database()

    with engine.begin() as connection:
        assert connection.execute(
            sql_text("SELECT count(*) FROM alembic_version")
        ).scalar() == 1
