from sqlalchemy import text

from app.db import engine


def test_database_is_reachable():
    with engine.connect() as connection:
        assert connection.execute(text("SELECT 1")).scalar() == 1


def test_alembic_version_table_exists_after_upgrade():
    with engine.connect() as connection:
        result = connection.execute(
            text(
                "SELECT COUNT(*) FROM information_schema.tables "
                "WHERE table_name = 'alembic_version'"
            )
        ).scalar()
    assert result == 1, "run: alembic upgrade head"


def test_no_schema_drift_between_the_models_and_the_migrations(db):
    """The models and the migrated schema must describe the same database.

    Caught a real one: `effective_range` is created by a migration and was not
    declared on the model, so Alembic saw a column the models did not have.
    The next --autogenerate would have written a migration DROPPING it - and
    the exclusion constraint that stops two affiliates owning one code goes
    with the column.

    Nothing would have failed. The constraint would simply have stopped
    existing, and the next overlapping registration would have been accepted.
    """
    from alembic import command
    from alembic.config import Config
    from alembic.util.exc import AutogenerateDiffsDetected

    try:
        command.check(Config("alembic.ini"))
    except AutogenerateDiffsDetected as drift:
        raise AssertionError(
            f"The models and the migrations disagree: {drift}\n"
            "Either add the missing migration, or declare the column on the "
            "model - but do not let --autogenerate decide, because its answer "
            "to an undeclared column is to drop it."
        ) from drift
