"""policy version

Revision ID: 0cf0101323e5
Revises: d4342bbcfa61
Create Date: 2026-09-01 19:05:43.250556

Phase 10 Batch C. `policy_version` did not exist before this - every rule this
platform has ever calculated under is, in effect, one policy that was never
written down as such. There is no v0 to distinguish it from, so this migration
both creates the table and writes the first row: **policy v1**, dated to
`GO_LIVE_MONTH`, describing today's rules in plain language. Every existing
`payroll_snapshot` is stamped with it - left `null` would make "which rules
applied here" a question the data cannot answer for the platform's own first
months, and a column nothing points at reads as a feature and is a lie
(app/models/payroll.py's own words, until this).
"""
import os
import re
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf0101323e5'
down_revision: Union[str, Sequence[str], None] = 'd4342bbcfa61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


POLICY_V1_TEXT = """\
## How commission works

**What counts toward commission.** Commission is worked out on what the \
customer actually paid for the goods — the total they paid, minus shipping \
and minus tax, after any discount their code gave them. If your code takes \
10% off, commission is on the 90% they actually paid, not on the shop price.

**When an order counts.** An order pays once it has been delivered with no \
open return or exchange. While it is still travelling, it is shown as \
"pending" so you can see it coming — it is not hidden, but it does not count \
yet. If a parcel is cancelled, fully refunded, or never delivered, it is void \
and pays nothing.

**Once delivered, the figure is fixed.** Whatever an order was worth the day \
it arrived is what it stays. A later exchange or partial return does not \
change what you already earned on it.

**Commission or a guaranteed minimum — never both, never stacked.** If your \
arrangement includes a guaranteed minimum, you are paid the larger of your \
commission or the guarantee for that month, not the guarantee on top of your \
commission. The guarantee only applies in a month where your targets were \
both met and confirmed by HBA. A month where a target was missed still pays \
your ordinary commission — missing a target is never a penalty, it only \
means the guarantee does not apply that month.

**An order from an earlier month, paid later.** If an order is still \
settling when its month closes, it is added to whichever month it actually \
pays in — at that earlier month's own rate, on top of whatever that later \
month is worth, never inside a guarantee comparison.

**Rounding.** What you are actually paid is always a whole pound. The exact \
figure, down to the piastre, is what the calculation produces; the amount \
transferred is that figure rounded to the nearest pound.
"""

_MONTH_PATTERN = re.compile(r"^\d{4}-(0[1-9]|1[0-2])$")


def _go_live_month() -> str | None:
    """The same variable the app itself reads - and the app already treats an
    empty one as legitimate (`test_me_reports_no_go_live_month_when_none_is_set`
    asserts exactly that), not a misconfiguration. This migration holds to the
    same standard: `None` here means "not decided yet," not "fail the deploy."
    """
    value = os.environ.get("GO_LIVE_MONTH", "").strip()
    return value if _MONTH_PATTERN.match(value) else None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('effective_month', sa.String(length=7), nullable=False),
    sa.Column('summary_markdown', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('effective_month', name='policy_version_effective_month_unique')
    )
    op.add_column('payroll_snapshot', sa.Column('policy_version_id', sa.Integer(), nullable=True))
    # Named explicitly - autogenerate left this `None`, which Postgres accepts
    # for create (it names the constraint itself) but downgrade() then has no
    # name to drop. Found by actually running the downgrade, not by reading it.
    op.create_foreign_key(
        'payroll_snapshot_policy_version_id_fkey',
        'payroll_snapshot', 'policy_version', ['policy_version_id'], ['id'],
        ondelete='RESTRICT',
    )
    # ### end Alembic commands ###

    # --- Data: policy v1, and every existing snapshot stamped with it -----
    #
    # Skipped, not failed, when GO_LIVE_MONTH is not yet set - a fresh
    # database (this test suite's, or a deployment before the business has
    # configured it) has no snapshots to backfill and no go-live date to
    # date a policy from either. The column stays nullable for exactly this:
    # `active_policy_for` returns None until someone creates the first real
    # version, the same as it would for any month before any policy existed.
    go_live_month = _go_live_month()
    if go_live_month is not None:
        policy_version = sa.table(
            "policy_version",
            sa.column("id", sa.Integer),
            sa.column("effective_month", sa.String),
            sa.column("summary_markdown", sa.Text),
        )
        connection = op.get_bind()
        result = connection.execute(
            policy_version.insert()
            .values(effective_month=go_live_month, summary_markdown=POLICY_V1_TEXT)
            .returning(policy_version.c.id)
        )
        policy_id = result.scalar_one()
        connection.execute(
            sa.text(
                "UPDATE payroll_snapshot SET policy_version_id = :policy_id "
                "WHERE policy_version_id IS NULL"
            ),
            {"policy_id": policy_id},
        )
        print(f"policy_version: created v1 effective {go_live_month}")
    else:
        print("policy_version: GO_LIVE_MONTH not set - no v1 created, table left empty")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'payroll_snapshot_policy_version_id_fkey', 'payroll_snapshot', type_='foreignkey'
    )
    op.drop_column('payroll_snapshot', 'policy_version_id')
    op.drop_table('policy_version')
    # ### end Alembic commands ###
