"""payroll month and snapshot

Revision ID: 31998d2af5d6
Revises: 6d5cff496410
Create Date: 2026-08-26 16:33:39.339366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31998d2af5d6'
down_revision: Union[str, Sequence[str], None] = '6d5cff496410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Where a figure stops being a calculation and becomes an obligation.

    payroll_snapshot is append-only, reusing reject_mutation() from the Phase 1
    guards. Two triggers, not one: a row-level BEFORE UPDATE OR DELETE trigger
    does NOT fire on TRUNCATE, so without the statement-level guard a single
    TRUNCATE would erase every frozen payroll figure silently.

    payroll_month is deliberately NOT append-only. Its state changes - that is
    the whole point of it - and the frozen thing is the snapshot it points at.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_month',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('calculation_state', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('active_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("calculation_state IN ('historical', 'draft', 'approved')", name='payroll_month_state_valid'),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliate_profile.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('affiliate_id', 'month', name='payroll_month_one_per_month')
    )
    op.create_index('payroll_month_month_idx', 'payroll_month', ['month'], unique=False)
    op.create_table('payroll_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_month_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('approved_obligation_piastres', sa.BigInteger(), nullable=False),
    sa.Column('exact_unrounded_piastres', sa.String(length=40), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('mod(approved_obligation_piastres, 100) = 0', name='payroll_snapshot_obligation_is_whole_pounds'),
    sa.CheckConstraint('approved_obligation_piastres >= 0', name='payroll_snapshot_obligation_not_negative'),
    sa.CheckConstraint('version >= 1', name='payroll_snapshot_version_positive'),
    sa.ForeignKeyConstraint(['approved_by'], ['user_account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payroll_month_id'], ['payroll_month.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_month_id', 'version', name='payroll_snapshot_version_unique')
    )
    op.create_index('payroll_snapshot_month_idx', 'payroll_snapshot', ['payroll_month_id'], unique=False)
    # ### end Alembic commands ###

    # Added by ALTER, because the two tables reference each other and neither
    # can be created with a foreign key to a table that does not exist yet.
    op.create_foreign_key(
        "payroll_month_active_snapshot_fkey",
        "payroll_month",
        "payroll_snapshot",
        ["active_snapshot_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    op.execute(
        """
        CREATE TRIGGER payroll_snapshot_no_update_or_delete
        BEFORE UPDATE OR DELETE ON payroll_snapshot
        FOR EACH ROW EXECUTE FUNCTION reject_mutation();
        """
    )
    op.execute(
        """
        CREATE TRIGGER payroll_snapshot_no_truncate
        BEFORE TRUNCATE ON payroll_snapshot
        FOR EACH STATEMENT EXECUTE FUNCTION reject_mutation();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "payroll_month_active_snapshot_fkey", "payroll_month", type_="foreignkey"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS payroll_snapshot_no_truncate ON payroll_snapshot;"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS payroll_snapshot_no_update_or_delete "
        "ON payroll_snapshot;"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('payroll_snapshot_month_idx', table_name='payroll_snapshot')
    op.drop_table('payroll_snapshot')
    op.drop_index('payroll_month_month_idx', table_name='payroll_month')
    op.drop_table('payroll_month')
    # ### end Alembic commands ###
