"""password reset

Revision ID: 51cceec9c73f
Revises: b7c4e1a92f30
Create Date: 2026-09-02 19:55:53.269758

The way back into an account whose password is lost. There was none: no reset
route existed anywhere in the API, and re-inviting was refused too, because
`create_invitation` turns away an address that already holds an account. A
model who forgot their password could only be helped by editing the database
by hand - which is survivable with one administrator and not with twenty
people, so this lands before any model is invited.

Nothing to backfill. An account with no reset row has simply never asked for
one, which is the ordinary state.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51cceec9c73f'
down_revision: Union[str, Sequence[str], None] = 'b7c4e1a92f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_reset_user_account_id'), 'password_reset', ['user_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_user_account_id'), table_name='password_reset')
    op.drop_table('password_reset')
    # ### end Alembic commands ###
