"""compensation period

Revision ID: 53c97d980f4a
Revises: dfcd5b625644
Create Date: 2026-08-24 21:49:34.776027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53c97d980f4a'
down_revision: Union[str, Sequence[str], None] = 'dfcd5b625644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Pay terms over time.

    Alembic writes the table and its check constraints, including the one
    saying which money fields each compensation type may carry. The no-overlap
    exclusion constraint is added below, because it is not something Alembic
    can infer from the model.
    """
    op.create_table('compensation_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=False),
    sa.Column('start_month', sa.String(length=7), nullable=False),
    sa.Column('end_month', sa.String(length=7), nullable=True),
    sa.Column('compensation_type', sa.String(length=30), nullable=False),
    sa.Column('commission_rate_bp', sa.Integer(), nullable=False),
    sa.Column('fixed_amount_piastres', sa.BigInteger(), nullable=True),
    sa.Column('base_amount_piastres', sa.BigInteger(), nullable=True),
    sa.Column('expected_customer_discount_bp', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_range', postgresql.DATERANGE(), sa.Computed("daterange(\n        make_date(left(start_month, 4)::int, right(start_month, 2)::int, 1),\n        CASE WHEN end_month IS NULL THEN NULL\n             ELSE make_date(\n                 right(end_month, 2)::int / 12 + left(end_month, 4)::int,\n                 mod(right(end_month, 2)::int, 12) + 1,\n                 1\n             )\n        END,\n        '[)'\n    )", persisted=True), nullable=True),
    sa.CheckConstraint("\n(\n  (compensation_type = 'commission'\n     AND fixed_amount_piastres IS NULL\n     AND base_amount_piastres IS NULL)\n  OR (compensation_type = 'fixed_plus_commission'\n     AND fixed_amount_piastres IS NOT NULL\n     AND base_amount_piastres IS NULL)\n  OR (compensation_type = 'base_guarantee'\n     AND base_amount_piastres IS NOT NULL\n     AND fixed_amount_piastres IS NULL)\n)\n", name='compensation_period_fields_match_type'),
    sa.CheckConstraint("compensation_type IN ('base_guarantee', 'commission', 'fixed_plus_commission')", name='compensation_period_type_valid'),
    sa.CheckConstraint('base_amount_piastres IS NULL OR base_amount_piastres >= 0', name='compensation_period_base_not_negative'),
    sa.CheckConstraint('commission_rate_bp > 0 AND commission_rate_bp <= 10000', name='compensation_period_rate_sane'),
    sa.CheckConstraint('end_month IS NULL OR end_month >= start_month', name='compensation_period_months_ordered'),
    sa.CheckConstraint('fixed_amount_piastres IS NULL OR fixed_amount_piastres >= 0', name='compensation_period_fixed_not_negative'),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliate_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('compensation_period_affiliate_idx', 'compensation_period', ['affiliate_id'], unique=False)
    # ### end Alembic commands ###

    # Two sets of pay terms in force for one affiliate in one month is not a
    # question with an answer, so it is made impossible rather than checked.
    #
    # Keyed on (affiliate_id, effective_range), unlike discount codes: two
    # different affiliates holding overlapping terms is entirely normal, while
    # two affiliates holding one code is the thing that pays the wrong person.
    op.execute(
        """
        ALTER TABLE compensation_period
        ADD CONSTRAINT compensation_period_no_overlap
        EXCLUDE USING gist (affiliate_id WITH =, effective_range WITH &&)
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('compensation_period_affiliate_idx', table_name='compensation_period')
    op.drop_table('compensation_period')
    # ### end Alembic commands ###
