"""payment ledger

Revision ID: 6285abebe4ed
Revises: a15ffe1f68bf
Create Date: 2026-08-26 17:35:57.734233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6285abebe4ed'
down_revision: Union[str, Sequence[str], None] = 'a15ffe1f68bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """The record that money actually moved.

    All three tables are append-only (section 17): a payment that can be edited
    is a payment nobody can reconcile against a bank statement. Corrections are
    payroll_adjustment rows, which say what they are.

    Two triggers each, not one. A row-level BEFORE UPDATE OR DELETE trigger does
    NOT fire on TRUNCATE, so without the statement-level guard a single TRUNCATE
    would erase the whole payment history silently.

    And one trigger that is not about append-only: section 17 requires that the
    sum of allocations never exceeds the transaction they belong to. That is a
    cross-row rule, so a CHECK constraint cannot express it - "we allocated
    E£12,000 of a E£10,000 transfer" has to be impossible rather than caught in
    review.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=False),
    sa.Column('amount_piastres', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('destination_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('proof_file_id', sa.String(length=64), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_piastres > 0', name='payment_transaction_amount_positive'),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliate_profile.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('payment_transaction_affiliate_idx', 'payment_transaction', ['affiliate_id'], unique=False)
    op.create_table('payroll_adjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('source_payroll_month_id', sa.Integer(), nullable=False),
    sa.Column('destination_payroll_month_id', sa.Integer(), nullable=True),
    sa.Column('amount_piastres', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('credit', 'writeoff', 'correction')", name='payroll_adjustment_type_valid'),
    sa.CheckConstraint('amount_piastres > 0', name='payroll_adjustment_amount_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['destination_payroll_month_id'], ['payroll_month.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_payroll_month_id'], ['payroll_month.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('payroll_adjustment_source_idx', 'payroll_adjustment', ['source_payroll_month_id'], unique=False)
    op.create_table('payment_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_transaction_id', sa.Integer(), nullable=False),
    sa.Column('payroll_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('allocated_piastres', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allocated_piastres > 0', name='payment_allocation_amount_positive'),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transaction.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payroll_snapshot_id'], ['payroll_snapshot.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('payment_allocation_snapshot_idx', 'payment_allocation', ['payroll_snapshot_id'], unique=False)
    op.create_index('payment_allocation_transaction_idx', 'payment_allocation', ['payment_transaction_id'], unique=False)
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE OR REPLACE FUNCTION reject_over_allocation() RETURNS trigger AS $$
        DECLARE
            transfer bigint;
            allocated bigint;
        BEGIN
            SELECT amount_piastres INTO transfer
            FROM payment_transaction
            WHERE id = NEW.payment_transaction_id;

            SELECT coalesce(sum(allocated_piastres), 0) INTO allocated
            FROM payment_allocation
            WHERE payment_transaction_id = NEW.payment_transaction_id;

            IF allocated + NEW.allocated_piastres > transfer THEN
                RAISE EXCEPTION
                    'allocating % would take transaction % to % of a % transfer',
                    NEW.allocated_piastres,
                    NEW.payment_transaction_id,
                    allocated + NEW.allocated_piastres,
                    transfer
                    USING ERRCODE = 'restrict_violation';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER payment_allocation_within_the_transfer
        BEFORE INSERT ON payment_allocation
        FOR EACH ROW EXECUTE FUNCTION reject_over_allocation();
        """
    )

    op.execute(
        """
        CREATE TRIGGER payment_transaction_no_update_or_delete
        BEFORE UPDATE OR DELETE ON payment_transaction
        FOR EACH ROW EXECUTE FUNCTION reject_mutation();
        """
    )
    op.execute(
        """
        CREATE TRIGGER payment_transaction_no_truncate
        BEFORE TRUNCATE ON payment_transaction
        FOR EACH STATEMENT EXECUTE FUNCTION reject_mutation();
        """
    )

    op.execute(
        """
        CREATE TRIGGER payment_allocation_no_update_or_delete
        BEFORE UPDATE OR DELETE ON payment_allocation
        FOR EACH ROW EXECUTE FUNCTION reject_mutation();
        """
    )
    op.execute(
        """
        CREATE TRIGGER payment_allocation_no_truncate
        BEFORE TRUNCATE ON payment_allocation
        FOR EACH STATEMENT EXECUTE FUNCTION reject_mutation();
        """
    )

    op.execute(
        """
        CREATE TRIGGER payroll_adjustment_no_update_or_delete
        BEFORE UPDATE OR DELETE ON payroll_adjustment
        FOR EACH ROW EXECUTE FUNCTION reject_mutation();
        """
    )
    op.execute(
        """
        CREATE TRIGGER payroll_adjustment_no_truncate
        BEFORE TRUNCATE ON payroll_adjustment
        FOR EACH STATEMENT EXECUTE FUNCTION reject_mutation();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS payment_transaction_no_truncate ON payment_transaction;")
    op.execute(
        "DROP TRIGGER IF EXISTS payment_transaction_no_update_or_delete ON payment_transaction;"
    )
    op.execute("DROP TRIGGER IF EXISTS payment_allocation_no_truncate ON payment_allocation;")
    op.execute(
        "DROP TRIGGER IF EXISTS payment_allocation_no_update_or_delete ON payment_allocation;"
    )
    op.execute("DROP TRIGGER IF EXISTS payroll_adjustment_no_truncate ON payroll_adjustment;")
    op.execute(
        "DROP TRIGGER IF EXISTS payroll_adjustment_no_update_or_delete ON payroll_adjustment;"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS payment_allocation_within_the_transfer "
        "ON payment_allocation;"
    )
    op.execute("DROP FUNCTION IF EXISTS reject_over_allocation();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('payment_allocation_transaction_idx', table_name='payment_allocation')
    op.drop_index('payment_allocation_snapshot_idx', table_name='payment_allocation')
    op.drop_table('payment_allocation')
    op.drop_index('payroll_adjustment_source_idx', table_name='payroll_adjustment')
    op.drop_table('payroll_adjustment')
    op.drop_index('payment_transaction_affiliate_idx', table_name='payment_transaction')
    op.drop_table('payment_transaction')
    # ### end Alembic commands ###
