"""order index

Revision ID: 65a890a8a0d6
Revises: c16349c64e62
Create Date: 2026-08-23 15:45:51.276418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a890a8a0d6'
down_revision: Union[str, Sequence[str], None] = 'c16349c64e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_index',
    sa.Column('shopify_order_id', sa.String(length=32), nullable=False),
    sa.Column('shopify_order_gid', sa.String(length=120), nullable=True),
    sa.Column('order_number', sa.String(length=40), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_month', sa.String(length=7), nullable=False),
    sa.Column('updated_at_shopify', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('financial_status', sa.String(length=40), nullable=True),
    sa.Column('fulfillment_status', sa.String(length=40), nullable=True),
    sa.Column('discount_codes', sa.ARRAY(sa.String(length=120)), server_default='{}', nullable=False),
    sa.Column('subtotal_piastres', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_piastres', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('shipping_piastres', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('tax_piastres', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='EGP', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('shopify_order_id')
    )
    op.create_index('order_index_business_month_idx', 'order_index', ['business_month'], unique=False)
    op.create_index('order_index_discount_codes_idx', 'order_index', ['discount_codes'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('order_index_discount_codes_idx', table_name='order_index', postgresql_using='gin')
    op.drop_index('order_index_business_month_idx', table_name='order_index')
    op.drop_table('order_index')
    # ### end Alembic commands ###
