"""monthly target

Revision ID: 6d5cff496410
Revises: ea6565864418
Create Date: 2026-08-26 14:22:25.251274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5cff496410'
down_revision: Union[str, Sequence[str], None] = 'ea6565864418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('required_videos', sa.Integer(), nullable=False),
    sa.Column('required_stories', sa.Integer(), nullable=False),
    sa.Column('actual_videos', sa.Integer(), nullable=True),
    sa.Column('actual_stories', sa.Integer(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(actual_videos IS NULL OR actual_videos >= 0) AND (actual_stories IS NULL OR actual_stories >= 0)', name='monthly_target_actuals_not_negative'),
    sa.CheckConstraint('(actual_videos IS NULL) = (actual_stories IS NULL)', name='monthly_target_actuals_recorded_together'),
    sa.CheckConstraint('required_videos >= 0 AND required_stories >= 0', name='monthly_target_requirements_not_negative'),
    sa.CheckConstraint('verified_at IS NULL OR actual_videos IS NOT NULL', name='monthly_target_cannot_verify_the_unrecorded'),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliate_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['user_account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['user_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('affiliate_id', 'month', name='monthly_target_one_per_month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_target')
    # ### end Alembic commands ###
