"""attributed order

Revision ID: 9d96ff0adaae
Revises: e7f91548c3d9
Create Date: 2026-08-25 15:46:33.035206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d96ff0adaae'
down_revision: Union[str, Sequence[str], None] = 'e7f91548c3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """The second tier of section 10.2, plus the trigger that freezes two fields.

    affiliate_id and business_month are enforced here rather than in the
    service, because "orders never move between models" and "an order's month
    never shifts" are both invariants that a future endpoint written in a hurry
    would otherwise be free to break. Section 17 requires the first; the second
    is the same failure - money moving to a month it was not earned in.

    Note this is NOT reject_mutation(). This table is not append-only: the
    commission base legitimately moves while an order is pending, and only
    these two columns are held still.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributed_order',
    sa.Column('shopify_order_id', sa.String(length=32), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=False),
    sa.Column('business_month', sa.String(length=7), nullable=False),
    sa.Column('commission_base_piastres', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('refunded_merchandise_piastres', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('commission_state', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('base_frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('financial_status', sa.String(length=40), nullable=True),
    sa.Column('fulfillment_status', sa.String(length=40), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_status', sa.String(length=40), nullable=True),
    sa.Column('attributed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("commission_state IN ('pending', 'earned', 'void')", name='attributed_order_state_valid'),
    sa.CheckConstraint('commission_base_piastres >= 0', name='attributed_order_base_not_negative'),
    sa.CheckConstraint('refunded_merchandise_piastres >= 0', name='attributed_order_refund_not_negative'),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliate_profile.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shopify_order_id'], ['order_index.shopify_order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shopify_order_id')
    )
    op.create_index('attributed_order_affiliate_month_idx', 'attributed_order', ['affiliate_id', 'business_month'], unique=False)
    op.create_index('attributed_order_business_month_idx', 'attributed_order', ['business_month'], unique=False)
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE OR REPLACE FUNCTION reject_attribution_change() RETURNS trigger AS $$
        BEGIN
            IF NEW.affiliate_id IS DISTINCT FROM OLD.affiliate_id THEN
                RAISE EXCEPTION
                    'order % belongs to affiliate %; orders never move between models',
                    OLD.shopify_order_id, OLD.affiliate_id
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF NEW.business_month IS DISTINCT FROM OLD.business_month THEN
                RAISE EXCEPTION
                    'order % was placed in %; changing it would move money between months',
                    OLD.shopify_order_id, OLD.business_month
                    USING ERRCODE = 'restrict_violation';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER attributed_order_attribution_is_immutable
        BEFORE UPDATE ON attributed_order
        FOR EACH ROW EXECUTE FUNCTION reject_attribution_change();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "DROP TRIGGER IF EXISTS attributed_order_attribution_is_immutable "
        "ON attributed_order;"
    )
    op.execute("DROP FUNCTION IF EXISTS reject_attribution_change();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('attributed_order_business_month_idx', table_name='attributed_order')
    op.drop_index('attributed_order_affiliate_month_idx', table_name='attributed_order')
    op.drop_table('attributed_order')
    # ### end Alembic commands ###
