"""settled in snapshot

Revision ID: a15ffe1f68bf
Revises: 31998d2af5d6
Create Date: 2026-08-26 16:36:20.756126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15ffe1f68bf'
down_revision: Union[str, Sequence[str], None] = '31998d2af5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attributed_order', sa.Column('settled_in_snapshot_id', sa.Integer(), nullable=True))
    op.add_column('attributed_order', sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'attributed_order', 'payroll_snapshot', ['settled_in_snapshot_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attributed_order', type_='foreignkey')
    op.drop_column('attributed_order', 'settled_at')
    op.drop_column('attributed_order', 'settled_in_snapshot_id')
    # ### end Alembic commands ###
