"""affiliate profile

Revision ID: b66a237ed72f
Revises: a379c1f73567
Create Date: 2026-08-24 20:37:48.946994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b66a237ed72f'
down_revision: Union[str, Sequence[str], None] = 'a379c1f73567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """The affiliate registry.

    user_account_id is unique and NOT NULL: one profile per account, and the
    account always exists first. An invitation creates nothing; accepting it
    creates the account, and the profile is filled in from there.

    ON DELETE CASCADE, with passive_deletes on the relationship - without it
    SQLAlchemy tries to NULL the foreign key before deleting, which violates
    NOT NULL and fails the delete outright.
    """
    op.create_table('affiliate_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('account_kind', sa.String(length=20), server_default='model', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("account_kind IN ('house', 'model')", name='affiliate_profile_kind_valid'),
    sa.CheckConstraint("status IN ('active', 'archived', 'inactive', 'pending')", name='affiliate_profile_status_valid'),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_account_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affiliate_profile')
    # ### end Alembic commands ###
