"""notification outbox

Section 16: every email is written here in the same transaction as the change
that caused it, so the month and the notice about it commit together or not at
all. Mutable, unlike integration_event and audit_event - this is a queue, and a
queue nothing can update is not a queue.

Revision ID: d4342bbcfa61
Revises: efa3aafbd50c
Create Date: 2026-08-27 21:12:02.372897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4342bbcfa61'
down_revision: Union[str, Sequence[str], None] = 'efa3aafbd50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('recipient_email', sa.String(length=320), nullable=False),
    sa.Column('recipient_name', sa.String(length=120), nullable=True),
    sa.Column('subject_ref', sa.String(length=80), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('pending', 'sent', 'failed', 'skipped')", name='notification_outbox_state_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_outbox_subject_ref'), 'notification_outbox', ['subject_ref'], unique=False)
    op.create_index('notification_outbox_pending_idx', 'notification_outbox', ['state', 'id'], unique=False, postgresql_where=sa.text("state = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('notification_outbox_pending_idx', table_name='notification_outbox', postgresql_where=sa.text("state = 'pending'"))
    op.drop_index(op.f('ix_notification_outbox_subject_ref'), table_name='notification_outbox')
    op.drop_table('notification_outbox')
    # ### end Alembic commands ###
