"""discount code period

Revision ID: dfcd5b625644
Revises: 01ce746ccf60
Create Date: 2026-08-24 21:23:34.188891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfcd5b625644'
down_revision: Union[str, Sequence[str], None] = '01ce746ccf60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Discount code ownership over time.

    Alembic writes the table; the generated range and the exclusion constraint
    are added below, because neither is something it can infer from the model.
    """
    op.create_table('discount_code_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('start_month', sa.String(length=7), nullable=False),
    sa.Column('end_month', sa.String(length=7), nullable=True),
    sa.Column('shopify_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_month IS NULL OR end_month >= start_month', name='discount_code_period_months_ordered'),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliate_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('discount_code_period_affiliate_idx', 'discount_code_period', ['affiliate_id'], unique=False)
    op.create_index('discount_code_period_code_idx', 'discount_code_period', ['code'], unique=False)
    # ### end Alembic commands ###

    # The generated range. Written out literally rather than imported from
    # app.core.periods: a migration is frozen in time and must not change
    # meaning because that module later did. periods.py holds the canonical
    # copy, and tests/test_periods.py proves the semantics.
    #
    # Built from make_date and integer arithmetic because a generated column
    # must be immutable, and text::date is not - date parsing depends on the
    # session's DateStyle, so Postgres refuses the column outright.
    op.execute(
        """
        ALTER TABLE discount_code_period
        ADD COLUMN effective_range daterange
        GENERATED ALWAYS AS (daterange(
        make_date(left(start_month, 4)::int, right(start_month, 2)::int, 1),
        CASE WHEN end_month IS NULL THEN NULL
             ELSE make_date(
                 right(end_month, 2)::int / 12 + left(end_month, 4)::int,
                 right(end_month, 2)::int % 12 + 1,
                 1
             )
        END,
        '[)'
    )) STORED
        """
    )

    # The constraint this whole task exists for.
    #
    # Keyed on `code` alone, deliberately NOT on (affiliate_id, code). Two
    # affiliates owning the same code in overlapping months is precisely the
    # situation that pays the wrong person - and a constraint on the pair would
    # permit exactly that while looking careful.
    op.execute(
        """
        ALTER TABLE discount_code_period
        ADD CONSTRAINT discount_code_period_no_overlap
        EXCLUDE USING gist (code WITH =, effective_range WITH &&)
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('discount_code_period_code_idx', table_name='discount_code_period')
    op.drop_index('discount_code_period_affiliate_idx', table_name='discount_code_period')
    op.drop_table('discount_code_period')
    # ### end Alembic commands ###
