"""attributed order needs review

Revision ID: e073a88aba50
Revises: e896368ceee3
Create Date: 2026-08-25 23:07:24.621825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e073a88aba50'
down_revision: Union[str, Sequence[str], None] = 'e896368ceee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attributed_order', sa.Column('needs_review', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attributed_order', 'needs_review')
    # ### end Alembic commands ###
