"""invitation withdrawn state

Telling a cancelled invitation apart from one nobody opened in time.

Withdrawing backdates `expires_at` so the link dies through the same check
accepting already applies - one rule rather than two that could disagree. The
cost was that afterwards both read "Link expired", and only one of them is
worth resending.

Nothing to backfill. Every existing row is null, which reads as "lapsed rather
than withdrawn" - true for the ones nobody opened, and unknowable for any that
were cancelled before this column existed. Guessing would be worse than
admitting it.


Revision ID: e0d115c57f7e
Revises: 51cceec9c73f
Create Date: 2026-09-02 23:24:25.949298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d115c57f7e'
down_revision: Union[str, Sequence[str], None] = '51cceec9c73f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation', sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitation', 'withdrawn_at')
    # ### end Alembic commands ###
