"""order delivery returns and refunds

Revision ID: e896368ceee3
Revises: 9d96ff0adaae
Create Date: 2026-08-25 16:45:38.273259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e896368ceee3'
down_revision: Union[str, Sequence[str], None] = '9d96ff0adaae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """What an order needs before it can be worth money.

    Every existing row gets NULL delivery facts and zero refunds. That is
    honest rather than convenient - the platform has genuinely never asked
    Shopify for these fields - but it means **the 529 orders already indexed
    know nothing about delivery until they are re-synced**, and an order with
    no delivery state never earns.

    The reconciliation sweep refreshes recent orders on its own. Anything older
    than its window needs the historical import run again. See docs/limits.md.

    The two refund columns default to 0 rather than NULL because "no refund"
    and "we never asked" are the same thing for money: nothing was returned.
    Delivery is the opposite - "not delivered" and "unknown" must stay
    distinguishable, or an unsynced order would look like a failed one.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_index', sa.Column('delivery_state', sa.String(length=16), nullable=True))
    op.add_column('order_index', sa.Column('delivery_status', sa.String(length=40), nullable=True))
    op.add_column('order_index', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('order_index', sa.Column('return_status', sa.String(length=40), nullable=True))
    op.add_column('order_index', sa.Column('return_open', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('order_index', sa.Column('refunded_total_piastres', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('order_index', sa.Column('refunded_merchandise_piastres', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_index', 'refunded_merchandise_piastres')
    op.drop_column('order_index', 'refunded_total_piastres')
    op.drop_column('order_index', 'return_open')
    op.drop_column('order_index', 'return_status')
    op.drop_column('order_index', 'delivered_at')
    op.drop_column('order_index', 'delivery_status')
    op.drop_column('order_index', 'delivery_state')
    # ### end Alembic commands ###
