"""delivery is final, so nothing is held

Revision ID: ea6565864418
Revises: e073a88aba50
Create Date: 2026-08-26 01:58:23.331443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea6565864418'
down_revision: Union[str, Sequence[str], None] = 'e073a88aba50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attributed_order', 'needs_review')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attributed_order', sa.Column('needs_review', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
