"""integration event and background job

Revision ID: eca106cab1f7
Revises: 65a890a8a0d6
Create Date: 2026-08-23 16:48:11.262649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eca106cab1f7'
down_revision: Union[str, Sequence[str], None] = '65a890a8a0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the tables behind the durable job queue.

    integration_event stores a payload digest, not the payload (ADR 0020). The
    table is append-only, so anything it holds it holds forever; a full webhook
    body would be hundreds of megabytes a year in a table nothing can prune.

    Both indexes on background_job are partial, covering only pending and
    running rows. Succeeded and failed jobs are never leased and are the bulk
    of the table over time, so indexing them would be storing rows the query
    excludes. The partial unique index on dedupe_key is what makes "at most one
    outstanding job per order" a database guarantee rather than a race.
    """
    op.create_table('background_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('leased_by', sa.String(length=80), nullable=True),
    sa.Column('leased_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed')", name='background_job_status_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('background_job_dedupe_idx', 'background_job', ['dedupe_key'], unique=True, postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.create_index('background_job_runnable_idx', 'background_job', ['status', 'run_after'], unique=False, postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.create_table('integration_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('payload_digest', sa.String(length=64), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='integration_event_identity')
    )
    op.create_index(op.f('ix_integration_event_entity_id'), 'integration_event', ['entity_id'], unique=False)
    op.create_index(op.f('ix_integration_event_received_at'), 'integration_event', ['received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_event_received_at'), table_name='integration_event')
    op.drop_index(op.f('ix_integration_event_entity_id'), table_name='integration_event')
    op.drop_table('integration_event')
    op.drop_index('background_job_runnable_idx', table_name='background_job', postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_index('background_job_dedupe_idx', table_name='background_job', postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_table('background_job')
    # ### end Alembic commands ###
