"""Discount code ownership, over time.

A code belongs to an affiliate *for some months*. Ask who owned ``NOUR10`` in
April and the answer must be a fact, because in Phase 4 that answer becomes
money.

**The exclusion constraint is on ``code`` alone, not on
``(affiliate_id, code)``.** Two affiliates owning the same code in overlapping
months is precisely the situation that pays the wrong person, so it must be
impossible - and a constraint keyed on the pair would permit exactly that while
looking careful.

Codes are stored upper-case. ``normalise_order`` already upper-cases what
Shopify sends, and a lookup that misses on case attributes nothing, silently
(§10.4). Storing the canonical form is also what makes the overlap constraint
work: ``nour10`` and ``NOUR10`` have to collide, or two affiliates could own one
code by typing it differently.
"""

from datetime import datetime

from sqlalchemy import (
    CheckConstraint,
    Computed,
    DateTime,
    ForeignKey,
    Index,
    String,
    text,
)
from sqlalchemy.dialects.postgresql import DATERANGE
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.periods import EFFECTIVE_RANGE_SQL
from app.db import Base


class DiscountCodePeriod(Base):
    """One affiliate's ownership of one code, for a run of months."""

    __tablename__ = "discount_code_period"
    __table_args__ = (
        CheckConstraint(
            "end_month IS NULL OR end_month >= start_month",
            name="discount_code_period_months_ordered",
        ),
        Index("discount_code_period_code_idx", "code"),
        Index("discount_code_period_affiliate_idx", "affiliate_id"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    affiliate_id: Mapped[int] = mapped_column(
        ForeignKey("affiliate_profile.id", ondelete="CASCADE"), nullable=False
    )

    #: Stored upper-case. See the module docstring.
    code: Mapped[str] = mapped_column(String(120), nullable=False)

    start_month: Mapped[str] = mapped_column(String(7), nullable=False)
    #: NULL means open-ended: from the start month, until further notice.
    end_month: Mapped[str | None] = mapped_column(String(7))

    #: **When** Shopify confirmed the code exists, not merely whether. §10.4
    #: makes verification a required gate before approval, and "verified, but
    #: eight months ago" is a different answer that a boolean cannot express.
    shopify_verified_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True)
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )

    #: Generated by the database from the two months above; the exclusion
    #: constraint is built on it.
    #:
    #: Declared here even though the migration creates it, because otherwise
    #: Alembic sees a column the model does not have and the next
    #: --autogenerate writes a migration that DROPS it - taking the overlap
    #: constraint with it, silently. Guarded by test_no_schema_drift.
    effective_range: Mapped[object] = mapped_column(
        DATERANGE, Computed(EFFECTIVE_RANGE_SQL, persisted=True), nullable=True
    )

    affiliate = relationship("AffiliateProfile", lazy="joined")

    @property
    def is_verified(self) -> bool:
        return self.shopify_verified_at is not None

    def __repr__(self) -> str:
        end = self.end_month or "onward"
        return f"<DiscountCodePeriod {self.code} {self.start_month}..{end}>"
